### ISSUE TITLE
Req.session must be an object 

### ISSUE THREAD

**Issue by dsmorris85** [oauth-io/sdk-node#20]
Receiving 'Error: req.session must be an object (did you used a session middleware?)' error when attempting to follow examples in documentation (using Node.js). My code is below, all dependencies installed I think. 

Apologies if this is the wrong place to post.

```
// Example with Linkedin
app.get('/signin', OAuth.auth('linkedin', 'MY_APP_URL/oauth/redirect'));

app.get('/oauth/redirect', OAuth.redirect(function(result, req, res) {
    if (result instanceof Error) {
        res.send(500, "error: " + result.message);
    }
    result.me().done(function(me) {
        console.log(me);
        res.send(200, JSON.stringify(me));
    });
}));

```

**Comment by bumpmann** [comment]
This looks like you are missing a session middleware => if you are using express you can use https://github.com/expressjs/session

**Comment by dsmorris85** [comment]
Thanks
